#Requires -RunAsAdministrator

# If (-NOT ([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator")) {   
#    Write-Host "Must be run with administrative rights. Ending script." -ForegroundColor Red
#    Break
#}

$Policy = "RemoteSigned"
If ((get-ExecutionPolicy) -ne $Policy) {
    Set-ExecutionPolicy $Policy -Force
}

[Net.ServicePointManager]::SecurityProtocol = "tls12"

# Download specific version of RZUpdate.exe
# $tag = '1.6.2.13'
# $uri = "https://github.com/rzander/ruckzuck/releases/download/$tag/RZUpdate.exe"
# $file = "RZUpdate.exe"
# Download Package
#    Invoke-WebRequest -Uri $uri -Method get -OutFile $env:temp\$file
#    Unblock-File $env:temp\$file

# Download latest RZUpdate.exe from rzander/ruckzuck release from github
# Reference: https://gist.github.com/MarkTiedemann/c0adc1701f3f5c215fc2c2d5b1d5efd3
$repo = "rzander/ruckzuck"
$file = "RZUpdate.exe"
$releases = "https://api.github.com/repos/$repo/releases/latest"

Write-Host Determining latest release
$tag = (Invoke-WebRequest $releases -UseBasicParsing | ConvertFrom-Json)[0].tag_name

$download = "https://github.com/$repo/releases/download/$tag/$file"

Write-Host Dowloading: RZUpdate.exe $tag
Invoke-WebRequest $download -OutFile $env:temp\$file -UseBasicParsing
Unblock-File $env:temp\$file

Start-Process -FilePath $env:temp\$file -ArgumentList "/Update"  -NoNewWindow -wait

#Delete desktop shortcuts in public folder
if (Get-Item "$env:Public\Desktop\*.lnk") {
Remove-Item -path "C:\users\Public\Desktop\" -include "*.lnk"
}
 
# Remove file
Remove-Item $env:temp\$file -Force

# SIG # Begin signature block
# MIIdgAYJKoZIhvcNAQcCoIIdcTCCHW0CAQExCzAJBgUrDgMCGgUAMGkGCisGAQQB
# gjcCAQSgWzBZMDQGCisGAQQBgjcCAR4wJgIDAQAABBAfzDtgWUsITrck0sYpfvNR
# AgEAAgEAAgEAAgEAAgEAMCEwCQYFKw4DAhoFAAQU82Y73/i0YkmlLPUgxzdPFiGR
# ZWGgghilMIIFczCCBFugAwIBAgIQd9JpaR46t3rAhZ9QvufvwDANBgkqhkiG9w0B
# AQsFADB8MQswCQYDVQQGEwJVUzELMAkGA1UECBMCTUkxEjAQBgNVBAcTCUFubiBB
# cmJvcjESMBAGA1UEChMJSW50ZXJuZXQyMREwDwYDVQQLEwhJbkNvbW1vbjElMCMG
# A1UEAxMcSW5Db21tb24gUlNBIENvZGUgU2lnbmluZyBDQTAeFw0xOTA1MDgwMDAw
# MDBaFw0yMjA1MDcyMzU5NTlaMIGtMQswCQYDVQQGEwJVUzEOMAwGA1UEEQwFOTgx
# OTUxCzAJBgNVBAgMAldBMRAwDgYDVQQHDAdTZWF0dGxlMRkwFwYDVQQJDBA0NTQ1
# IDE1dGggQXZlIE5FMSEwHwYDVQQKDBhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0b24x
# DjAMBgNVBAsMBVVXLUlUMSEwHwYDVQQDDBhVbml2ZXJzaXR5IG9mIFdhc2hpbmd0
# b24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQDGxM+yklmH0esOzsyT
# vg4KhP8OF+EY6atNBDCVvmG97KIC0UAjJuUmne8lOFY6iI/Pc5pJnWvz6wv6LSDP
# WjMKl/Hgst0ZL11GEOTUTBzs2BrLAPJ9NCjwKR3NK16VQCdeSWwxV6L4I/RU+JKL
# 4j96UYI3+b3x8ka+EQW0scvN5xS5hvVL3J35nr6q6gxXQBcW6C6iJKzHqFczTtHE
# XJqmvHS2SDNMkhWeIZ0t+vghmxrxOB7aff8a88SdR8Dphv1whhELswthEfGzZ/O4
# 1m4OiBkqOCwIvGgISStHv0e+RQ8xcOTg1SWC3RIPccVVPvUv50lEnboGZo5Onam3
# 1UBRAgMBAAGjggG9MIIBuTAfBgNVHSMEGDAWgBSuNSMX//8GPZxQ4IwkZTMecBCI
# ojAdBgNVHQ4EFgQUbwy96JcPNnJyZHA2GGfYvzDOMo8wDgYDVR0PAQH/BAQDAgeA
# MAwGA1UdEwEB/wQCMAAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwEQYJYIZIAYb4QgEB
# BAQDAgQQMGYGA1UdIARfMF0wWwYMKwYBBAGuIwEEAwIBMEswSQYIKwYBBQUHAgEW
# PWh0dHBzOi8vd3d3LmluY29tbW9uLm9yZy9jZXJ0L3JlcG9zaXRvcnkvY3BzX2Nv
# ZGVfc2lnbmluZy5wZGYwSQYDVR0fBEIwQDA+oDygOoY4aHR0cDovL2NybC5pbmNv
# bW1vbi1yc2Eub3JnL0luQ29tbW9uUlNBQ29kZVNpZ25pbmdDQS5jcmwwfgYIKwYB
# BQUHAQEEcjBwMEQGCCsGAQUFBzAChjhodHRwOi8vY3J0LmluY29tbW9uLXJzYS5v
# cmcvSW5Db21tb25SU0FDb2RlU2lnbmluZ0NBLmNydDAoBggrBgEFBQcwAYYcaHR0
# cDovL29jc3AuaW5jb21tb24tcnNhLm9yZzANBgkqhkiG9w0BAQsFAAOCAQEAg5jx
# nIY4Zo1Xcg390jO5DuwEynZxMS/ODfV3vTdaHempUIAwt3QNMpdIFbQDfzKPj3qc
# JREh95MJPbhs53oFYJfyo5JfXTaKtksaLGHtxwbfFzEmCguTfWT2u106hE4K54mv
# Lv6BTg+VnlR/AIO24kWXd9fqAsGj+lBFg0gRjss3qYxyWaAppIO4FcwVsGIHTIf8
# DBuiZ/9z7pWv+5pcw+WFFCHquQER2Q7VC64mM8ZTYZc7/K49GpAS+jJ/wSt8pSxm
# nQBwQPU10LVfD6HpkVa8fC9iHW+dwhVKHTs9bcVpeiILBEF1Qmlrqv2fKso/K+WC
# bhGPcBqdLMJsNBeKOTCCBeswggPToAMCAQICEGXh4uPV3lBFhfMmJIAF4tQwDQYJ
# KoZIhvcNAQENBQAwgYgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpOZXcgSmVyc2V5
# MRQwEgYDVQQHEwtKZXJzZXkgQ2l0eTEeMBwGA1UEChMVVGhlIFVTRVJUUlVTVCBO
# ZXR3b3JrMS4wLAYDVQQDEyVVU0VSVHJ1c3QgUlNBIENlcnRpZmljYXRpb24gQXV0
# aG9yaXR5MB4XDTE0MDkxOTAwMDAwMFoXDTI0MDkxODIzNTk1OVowfDELMAkGA1UE
# BhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNVBAoT
# CUludGVybmV0MjERMA8GA1UECxMISW5Db21tb24xJTAjBgNVBAMTHEluQ29tbW9u
# IFJTQSBDb2RlIFNpZ25pbmcgQ0EwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
# AoIBAQDAoC+LHnq7anWs+D7co7o5Isrzo3bkv30wJ+a605gyViNcBoaXDYDo7aKB
# NesL9l5+qT5oc/2d1Gd5zqrqaLcZ2xx2OlmHXV6Zx6GyuKmEcwzMq4dGHGrH7zkl
# vqfd2iw1cDYdIi4gO93jHA4/NJ/lff5VgFsGfIJXhFXzOPvyDDapuV6yxYFHI30S
# gaDAASg+A/k4l6OtAvICaP3VAav11VFNUNMXIkblcxjgOuQ3d1HInn1Sik+A3Ca5
# wEzK/FH6EAkRelcqc8TgISpswlS9HD6D+FupLPH623jP2YmabaP/Dac/fkxWI9YJ
# vuGlHYsHxb/j31iq76SvgssF+AoJAgMBAAGjggFaMIIBVjAfBgNVHSMEGDAWgBRT
# eb9aqitKz1SA4dibwJ3ysgNmyzAdBgNVHQ4EFgQUrjUjF///Bj2cUOCMJGUzHnAQ
# iKIwDgYDVR0PAQH/BAQDAgGGMBIGA1UdEwEB/wQIMAYBAf8CAQAwEwYDVR0lBAww
# CgYIKwYBBQUHAwMwEQYDVR0gBAowCDAGBgRVHSAAMFAGA1UdHwRJMEcwRaBDoEGG
# P2h0dHA6Ly9jcmwudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FDZXJ0aWZpY2F0
# aW9uQXV0aG9yaXR5LmNybDB2BggrBgEFBQcBAQRqMGgwPwYIKwYBBQUHMAKGM2h0
# dHA6Ly9jcnQudXNlcnRydXN0LmNvbS9VU0VSVHJ1c3RSU0FBZGRUcnVzdENBLmNy
# dDAlBggrBgEFBQcwAYYZaHR0cDovL29jc3AudXNlcnRydXN0LmNvbTANBgkqhkiG
# 9w0BAQ0FAAOCAgEARiy2f2pOJWa9nGqmqtCevQ+uTjX88DgnwcedBMmCNNuG4RP3
# wZaNMEQT0jXtefdXXJOmEldtq3mXwSZk38lcy8M2om2TI6HbqjACa+q4wIXWkqJB
# bK4MOWXFH0wQKnrEXjCcfUxyzhZ4s6tA/L4LmRYTmCD/srpz0bVU3AuSX+mj05E+
# WPEop4WE+D35OLcnMcjFbst3KWN99xxaK40VHnX8EkcBkipQPDcuyt1hbOCDjHTq
# 2Ay84R/SchN6WkVPGpW8y0mGc59lul1dlDmjVOynF9MRU5ACynTkdQ0JfKHOeVUu
# vQlo2Qzt52CTn3OZ1NtIZ0yrxm267pXKuK86UxI9aZrLkyO/BPO42itvAG/QMv7t
# zJkGns1hmi74OgZ3WUVk3SNTkixAqCbf7TSmecnrtyt0XB/P/xurcyFOIo5YRvTg
# VPc5lWn6PO9oKEdYtDyBsI5GAKVpmrUfdqojsl5GRYQQSnpO/hYBWyv+LsuhdTva
# A5vwIDM8WrAjgTFx2vGnQjg5dsQIeUOpTixMierCUzCh+bF47i73jX3qoiolCX7x
# LKSXTpWS2oy7HzgjDdlAsfTwnwton5YNTJxzg6NjrUjsUbEIORtJB/eeld5EWbQg
# GfwaJb5NEOTonZckUtYS1VmaFugWUEuhSWodQIq7RA6FT/4AQ6qdj3yPbNEwggZq
# MIIFUqADAgECAhADAZoCOv9YsWvW1ermF/BmMA0GCSqGSIb3DQEBBQUAMGIxCzAJ
# BgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5k
# aWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IEFzc3VyZWQgSUQgQ0EtMTAe
# Fw0xNDEwMjIwMDAwMDBaFw0yNDEwMjIwMDAwMDBaMEcxCzAJBgNVBAYTAlVTMREw
# DwYDVQQKEwhEaWdpQ2VydDElMCMGA1UEAxMcRGlnaUNlcnQgVGltZXN0YW1wIFJl
# c3BvbmRlcjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAKNkXfx8s+CC
# NeDg9sYq5kl1O8xu4FOpnx9kWeZ8a39rjJ1V+JLjntVaY1sCSVDZg85vZu7dy4Xp
# X6X51Id0iEQ7Gcnl9ZGfxhQ5rCTqqEsskYnMXij0ZLZQt/USs3OWCmejvmGfrvP9
# Enh1DqZbFP1FI46GRFV9GIYFjFWHeUhG98oOjafeTl/iqLYtWQJhiGFyGGi5uHzu
# 5uc0LzF3gTAfuzYBje8n4/ea8EwxZI3j6/oZh6h+z+yMDDZbesF6uHjHyQYuRhDI
# jegEYNu8c3T6Ttj+qkDxss5wRoPp2kChWTrZFQlXmVYwk/PJYczQCMxr7GJCkawC
# wO+k8IkRj3cCAwEAAaOCAzUwggMxMA4GA1UdDwEB/wQEAwIHgDAMBgNVHRMBAf8E
# AjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUFBwMIMIIBvwYDVR0gBIIBtjCCAbIwggGh
# BglghkgBhv1sBwEwggGSMCgGCCsGAQUFBwIBFhxodHRwczovL3d3dy5kaWdpY2Vy
# dC5jb20vQ1BTMIIBZAYIKwYBBQUHAgIwggFWHoIBUgBBAG4AeQAgAHUAcwBlACAA
# bwBmACAAdABoAGkAcwAgAEMAZQByAHQAaQBmAGkAYwBhAHQAZQAgAGMAbwBuAHMA
# dABpAHQAdQB0AGUAcwAgAGEAYwBjAGUAcAB0AGEAbgBjAGUAIABvAGYAIAB0AGgA
# ZQAgAEQAaQBnAGkAQwBlAHIAdAAgAEMAUAAvAEMAUABTACAAYQBuAGQAIAB0AGgA
# ZQAgAFIAZQBsAHkAaQBuAGcAIABQAGEAcgB0AHkAIABBAGcAcgBlAGUAbQBlAG4A
# dAAgAHcAaABpAGMAaAAgAGwAaQBtAGkAdAAgAGwAaQBhAGIAaQBsAGkAdAB5ACAA
# YQBuAGQAIABhAHIAZQAgAGkAbgBjAG8AcgBwAG8AcgBhAHQAZQBkACAAaABlAHIA
# ZQBpAG4AIABiAHkAIAByAGUAZgBlAHIAZQBuAGMAZQAuMAsGCWCGSAGG/WwDFTAf
# BgNVHSMEGDAWgBQVABIrE5iymQftHt+ivlcNK2cCzTAdBgNVHQ4EFgQUYVpNJLZJ
# Mp1KKnkag0v0HonByn0wfQYDVR0fBHYwdDA4oDagNIYyaHR0cDovL2NybDMuZGln
# aWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEQ0EtMS5jcmwwOKA2oDSGMmh0dHA6
# Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRENBLTEuY3JsMHcG
# CCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0cDovL29jc3AuZGlnaWNlcnQu
# Y29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2FjZXJ0cy5kaWdpY2VydC5jb20vRGln
# aUNlcnRBc3N1cmVkSURDQS0xLmNydDANBgkqhkiG9w0BAQUFAAOCAQEAnSV+GzNN
# siaBXJuGziMgD4CH5Yj//7HUaiwx7ToXGXEXzakbvFoWOQCd42yE5FpA+94GAYw3
# +puxnSR+/iCkV61bt5qwYCbqaVchXTQvH3Gwg5QZBWs1kBCge5fH9j/n4hFBpr1i
# 2fAnPTgdKG86Ugnw7HBi02JLsOBzppLA044x2C/jbRcTBu7kA7YUq/OPQ6dxnSHd
# FMoVXZJB2vkPgdGZdA0mxA5/G7X1oPHGdwYoFenYk+VVFvC7Cqsc21xIJ2bIo4sK
# HOWV2q7ELlmgYd3a822iYemKC23sEhi991VUQAOSK2vCUcIKSK+w1G7g9BQKOhvj
# jz3Kr2qNe9zYRDCCBs0wggW1oAMCAQICEAb9+QOWA63qAArrPye7uhswDQYJKoZI
# hvcNAQEFBQAwZTELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZ
# MBcGA1UECxMQd3d3LmRpZ2ljZXJ0LmNvbTEkMCIGA1UEAxMbRGlnaUNlcnQgQXNz
# dXJlZCBJRCBSb290IENBMB4XDTA2MTExMDAwMDAwMFoXDTIxMTExMDAwMDAwMFow
# YjELMAkGA1UEBhMCVVMxFTATBgNVBAoTDERpZ2lDZXJ0IEluYzEZMBcGA1UECxMQ
# d3d3LmRpZ2ljZXJ0LmNvbTEhMB8GA1UEAxMYRGlnaUNlcnQgQXNzdXJlZCBJRCBD
# QS0xMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA6IItmfnKwkKVpYBz
# QHDSnlZUXKnE0kEGj8kz/E1FkVyBn+0snPgWWd+etSQVwpi5tHdJ3InECtqvy15r
# 7a2wcTHrzzpADEZNk+yLejYIA6sMNP4YSYL+x8cxSIB8HqIPkg5QycaH6zY/2DDD
# /6b3+6LNb3Mj/qxWBZDwMiEWicZwiPkFl32jx0PdAug7Pe2xQaPtP77blUjE7h6z
# 8rwMK5nQxl0SQoHhg26Ccz8mSxSQrllmCsSNvtLOBq6thG9IhJtPQLnxTPKvmPv2
# zkBdXPao8S+v7Iki8msYZbHBc63X8djPHgp0XEK4aH631XcKJ1Z8D2KkPzIUYJX9
# BwSiCQIDAQABo4IDejCCA3YwDgYDVR0PAQH/BAQDAgGGMDsGA1UdJQQ0MDIGCCsG
# AQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUFBwMEBggrBgEFBQcDCDCC
# AdIGA1UdIASCAckwggHFMIIBtAYKYIZIAYb9bAABBDCCAaQwOgYIKwYBBQUHAgEW
# Lmh0dHA6Ly93d3cuZGlnaWNlcnQuY29tL3NzbC1jcHMtcmVwb3NpdG9yeS5odG0w
# ggFkBggrBgEFBQcCAjCCAVYeggFSAEEAbgB5ACAAdQBzAGUAIABvAGYAIAB0AGgA
# aQBzACAAQwBlAHIAdABpAGYAaQBjAGEAdABlACAAYwBvAG4AcwB0AGkAdAB1AHQA
# ZQBzACAAYQBjAGMAZQBwAHQAYQBuAGMAZQAgAG8AZgAgAHQAaABlACAARABpAGcA
# aQBDAGUAcgB0ACAAQwBQAC8AQwBQAFMAIABhAG4AZAAgAHQAaABlACAAUgBlAGwA
# eQBpAG4AZwAgAFAAYQByAHQAeQAgAEEAZwByAGUAZQBtAGUAbgB0ACAAdwBoAGkA
# YwBoACAAbABpAG0AaQB0ACAAbABpAGEAYgBpAGwAaQB0AHkAIABhAG4AZAAgAGEA
# cgBlACAAaQBuAGMAbwByAHAAbwByAGEAdABlAGQAIABoAGUAcgBlAGkAbgAgAGIA
# eQAgAHIAZQBmAGUAcgBlAG4AYwBlAC4wCwYJYIZIAYb9bAMVMBIGA1UdEwEB/wQI
# MAYBAf8CAQAweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2Nz
# cC5kaWdpY2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2lj
# ZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwgYEGA1UdHwR6MHgw
# OqA4oDaGNGh0dHA6Ly9jcmwzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEFzc3VyZWRJ
# RFJvb3RDQS5jcmwwOqA4oDaGNGh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdp
# Q2VydEFzc3VyZWRJRFJvb3RDQS5jcmwwHQYDVR0OBBYEFBUAEisTmLKZB+0e36K+
# Vw0rZwLNMB8GA1UdIwQYMBaAFEXroq/0ksuCMS1Ri6enIZ3zbcgPMA0GCSqGSIb3
# DQEBBQUAA4IBAQBGUD7Jtygkpzgdtlspr1LPUukxR6tWXHvVDQtBs+/sdR90OPKy
# XGGinJXDUOSCuSPRujqGcq04eKx1XRcXNHJHhZRW0eu7NoR3zCSl8wQZVann4+er
# Ys37iy2QwsDStZS9Xk+xBdIOPRqpFFumhjFiqKgz5Js5p8T1zh14dpQlc+Qqq8+c
# dkvtX8JLFuRLcEwAiR78xXm8TBJX/l/hHrwCXaj++wc4Tw3GXZG5D2dFzdaD7eeS
# DY2xaYxP+1ngIw/Sqq4AfO6cQg7PkdcntxbuD8O9fAqg7iwIVYUiuOsYGk38KiGt
# STGDR5V3cdyxG0tLHBCcdxTBnU8vWpUIKRAmMYIERTCCBEECAQEwgZAwfDELMAkG
# A1UEBhMCVVMxCzAJBgNVBAgTAk1JMRIwEAYDVQQHEwlBbm4gQXJib3IxEjAQBgNV
# BAoTCUludGVybmV0MjERMA8GA1UECxMISW5Db21tb24xJTAjBgNVBAMTHEluQ29t
# bW9uIFJTQSBDb2RlIFNpZ25pbmcgQ0ECEHfSaWkeOrd6wIWfUL7n78AwCQYFKw4D
# AhoFAKB4MBgGCisGAQQBgjcCAQwxCjAIoAKAAKECgAAwGQYJKoZIhvcNAQkDMQwG
# CisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwIwYJKoZI
# hvcNAQkEMRYEFAfDTtA+d9ICauZJ4R8oRL3d5IxaMA0GCSqGSIb3DQEBAQUABIIB
# ALzT1ObxTd0Ksw12EeDGCr/WpVV4TVqhsyGh0sDEtsjkrtC343MInTdAZFoP1mhs
# TTLKmUO7CeXfujKy+VNfqNhIVy8/aOhKCae7BGXgYOAZ//sn8H/noq48OkuDWkzq
# 9Fh00tya9oYYWYNNUc4aIO/lyMke05tCRAjmr+bHvwI2dketp2h90MFzTCJtBox+
# NWnO9x6ORw5t8e6XDffoZ2i3XCG0QP760ucYzeGZWRD2cSlahpIR5zgxvnux8ASo
# htbOphIg5ZMWuE1dNMR7vocFqblK+UBxb1/saMlJQohRdh0C8kSmKuUhbgPehlGO
# tymUaHxH47g0XtLm/RB3wkqhggIPMIICCwYJKoZIhvcNAQkGMYIB/DCCAfgCAQEw
# djBiMQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMRkwFwYDVQQL
# ExB3d3cuZGlnaWNlcnQuY29tMSEwHwYDVQQDExhEaWdpQ2VydCBBc3N1cmVkIElE
# IENBLTECEAMBmgI6/1ixa9bV6uYX8GYwCQYFKw4DAhoFAKBdMBgGCSqGSIb3DQEJ
# AzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTE5MDUwOTE1NTcwOFowIwYJ
# KoZIhvcNAQkEMRYEFBdabMAnDAxDdR1KqDe2EGVm0D0VMA0GCSqGSIb3DQEBAQUA
# BIIBAAKPSfMzMPmmGxY4KKEFuDVx/f46m6uNQUWSrTxN4/32n2oM6F/dLK8pG71c
# GyMZN0p3n/VzwerZtkoi/94bGJX7+m5CAzZ5DbzmxeM2s3CEGjG/cyjd9BgWn8ze
# MbUvjDq7J5DCz2DeLooCwc3kNC50CAa3SXfEVjP7n9GG4yv4ptoJWmw2KLL/moO1
# ri/vKILj1TeML3GvG9YeRtQVGosA48TVVxY2EgEoevS/ySVUmwrl5+3Nj+AH+lSW
# EihYs23MMZG0dRaNYsX5Y2lYrxWgtAE0XUkSYGoi/6HekUobKObqPjEX6jg/hptH
# pNCzvWuBIYsj3N+9ev4yC8HL9Tg=
# SIG # End signature block
